name: kt2
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  freezed: ^2.5.7
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  lints: ^4.0.0
  test: ^1.24.0
